server:
  port: 6220
spring:
  application:
    name: drone
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
#      data-locations: classpath:data.sql
#Power Audit logging Frequency (in seconds)
drone:
  power:
    logger:
      frequency: 15