
-- #DRONE
INSERT INTO DRONE (SERIAL_NUMBER , BATTERY , MODEL , STATE , WEIGHT_LIMIT ) VALUES ('123456789', 30, 'LIGHTWEIGHT', 'IDLE', 5);
INSERT INTO DRONE (SERIAL_NUMBER , BATTERY , MODEL , STATE , WEIGHT_LIMIT ) VALUES ('123456788', 16, 'CRUISERWEIGHT', 'IDLE', 15);
INSERT INTO DRONE (SERIAL_NUMBER , BATTERY , MODEL , STATE , WEIGHT_LIMIT ) VALUES ('123456787', 98, 'MIDDLEWEIGHT', 'IDLE', 10);
INSERT INTO DRONE (SERIAL_NUMBER , BATTERY , MODEL , STATE , WEIGHT_LIMIT ) VALUES ('123456786', 12, 'LIGHTWEIGHT', 'IDLE', 7);
INSERT INTO DRONE (SERIAL_NUMBER , BATTERY , MODEL , STATE , WEIGHT_LIMIT ) VALUES ('123456785', 55, 'HEAVYWEIGHT', 'IDLE', 20);

--#MEDICATION